name: glados
description: 'A simple testing framework that tries to break your properties.'
version: 1.1.7

repository: https://github.com/MarcelGarus/glados

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  characters: ^1.3.0
  meta: ^1.11.0
  spec: ^0.2.3
  test: ^1.20.0

dev_dependencies:
  lints: ^4.0.0
